name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  node_version: 22.12.0

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - run: npm test
